/**
 * GIANT.JS
 * Build Date: 2026-05-08T07:26:29.584Z
 * Integrity: sha256-5f79380c6aba238f40b4eccf24342e1e6ccbb8fe68cdc6fbdf05927d5236425d
 */

export declare const design: {
  color: {
    readonly "surface": "color-surface";
    readonly "surfaceMuted": "color-surface-muted";
    readonly "surfaceRaised": "color-surface-raised";
    readonly "surfaceOverlay": "color-surface-overlay";
    readonly "placeholder": "color-placeholder";
    readonly "highlight": "color-highlight";
    readonly "neutral": readonly ["var(--color-neutral-0)", "var(--color-neutral-1)", "var(--color-neutral-2)", "var(--color-neutral-3)", "var(--color-neutral-4)", "var(--color-neutral-5)", "var(--color-neutral-6)", "var(--color-neutral-7)", "var(--color-neutral-8)", "var(--color-neutral-9)"];
    readonly "primary": readonly ["var(--color-primary-0)", "var(--color-primary-1)", "var(--color-primary-2)", "var(--color-primary-3)", "var(--color-primary-4)", "var(--color-primary-5)"];
    readonly "accent": readonly ["var(--color-accent-0)", "var(--color-accent-1)", "var(--color-accent-2)", "var(--color-accent-3)", "var(--color-accent-4)", "var(--color-accent-5)"];
    readonly "success": readonly ["var(--color-success-0)", "var(--color-success-1)", "var(--color-success-2)", "var(--color-success-3)", "var(--color-success-4)"];
    readonly "warning": readonly ["var(--color-warning-0)", "var(--color-warning-1)", "var(--color-warning-2)", "var(--color-warning-3)", "var(--color-warning-4)"];
    readonly "danger": readonly ["var(--color-danger-0)", "var(--color-danger-1)", "var(--color-danger-2)", "var(--color-danger-3)", "var(--color-danger-4)"];
  };
  bg: {
    readonly "bg": "bg";
    readonly "bgMuted": "bg-muted";
    readonly "bgSubtle": "bg-subtle";
    readonly "bgSurface": "bg-surface";
    readonly "bgSurfaceMuted": "bg-surface-muted";
    readonly "bgSurfaceRaised": "bg-surface-raised";
    readonly "bgSurfaceOverlay": "bg-surface-overlay";
    readonly "actionBg": "color-action-bg";
    readonly "accentBg": "color-accent-bg";
    readonly "bgAction": "bg-action";
    readonly "successBg": "color-success-bg";
    readonly "warningBg": "color-warning-bg";
    readonly "dangerBg": "color-danger-bg";
    readonly "inputBg": "color-input-bg";
    readonly "inverseBg": "color-inverse-bg";
  };
  fg: {
    readonly "fg": "fg";
    readonly "fgMuted": "fg-muted";
    readonly "fgSubtle": "fg-subtle";
    readonly "actionFg": "color-action-fg";
    readonly "accentFg": "color-accent-fg";
    readonly "fgAction": "fg-action";
    readonly "successFg": "color-success-fg";
    readonly "warningFg": "color-warning-fg";
    readonly "dangerFg": "color-danger-fg";
    readonly "inputFg": "color-input-fg";
    readonly "inverseFg": "color-inverse-fg";
  };
  border: {
    readonly "border": "border-color";
    readonly "borderMuted": "border-muted";
    readonly "borderStrong": "border-strong";
    readonly "actionBorder": "color-action-border";
    readonly "accentBorder": "color-accent-border";
    readonly "borderAction": "border-action";
    readonly "successBorder": "color-success-border";
    readonly "warningBorder": "color-warning-border";
    readonly "dangerBorder": "color-danger-border";
    readonly "inputBorder": "color-input-border";
  };
  layout: {
    readonly "block": "layout-block";
    readonly "inline": "layout-inline";
    readonly "inlineBlock": "layout-inline-block";
    readonly "flex": "layout-flex";
    readonly "inlineFlex": "layout-inline-flex";
    readonly "inlineGrid": "layout-inline-grid";
    readonly "grid": "layout-grid";
    readonly "none": "layout-none";
    readonly "static": "layout-static";
    readonly "relative": "layout-relative";
    readonly "absolute": "layout-absolute";
    readonly "fixed": "layout-fixed";
    readonly "sticky": "layout-sticky";
    readonly "inset0": "layout-inset-0";
    readonly "insetAuto": "layout-inset-auto";
    readonly "insetInline0": "layout-inset-inline-0";
    readonly "insetBlock0": "layout-inset-block-0";
    readonly "insetStart0": "layout-inset-start-0";
    readonly "insetEnd0": "layout-inset-end-0";
    readonly "zBase": "layout-z-base";
    readonly "zRaised": "layout-z-raised";
    readonly "zOverlay": "layout-z-overlay";
    readonly "zModal": "layout-z-modal";
    readonly "overflowVisible": "layout-overflow-visible";
    readonly "overflowHidden": "layout-overflow-hidden";
    readonly "overflowAuto": "layout-overflow-auto";
    readonly "overflowScroll": "layout-overflow-scroll";
    readonly "overflowClip": "layout-overflow-clip";
    readonly "overflowInlineAuto": "layout-overflow-inline-auto";
    readonly "overflowBlockAuto": "layout-overflow-block-auto";
    readonly "itemsCenter": "layout-items-center";
    readonly "justifyCenter": "layout-justify-center";
    readonly "justifyBetween": "layout-justify-between";
    readonly "justifyAround": "layout-justify-around";
    readonly "container": "layout-container";
    readonly "stack": "layout-stack";
    readonly "cluster": "layout-cluster";
    readonly "frame": "layout-frame";
    readonly "sidebar": "layout-sidebar";
    readonly "switcher": "layout-switcher";
  };
  spacing: {
    readonly "layoutGap0": "layout-gap-0";
    readonly "gap0": "gap-0";
    readonly "layoutGap1": "layout-gap-1";
    readonly "gap1": "gap-1";
    readonly "layoutGap2": "layout-gap-2";
    readonly "gap2": "gap-2";
    readonly "layoutGap3": "layout-gap-3";
    readonly "gap3": "gap-3";
    readonly "layoutGap4": "layout-gap-4";
    readonly "gap4": "gap-4";
    readonly "layoutGap5": "layout-gap-5";
    readonly "gap5": "gap-5";
    readonly "layoutGap6": "layout-gap-6";
    readonly "gap6": "gap-6";
    readonly "layoutGap7": "layout-gap-7";
    readonly "gap7": "gap-7";
    readonly "layoutGap8": "layout-gap-8";
    readonly "gap8": "gap-8";
    readonly "layoutPadding0": "layout-padding-0";
    readonly "p0": "p-0";
    readonly "layoutPadding1": "layout-padding-1";
    readonly "p1": "p-1";
    readonly "layoutPadding2": "layout-padding-2";
    readonly "p2": "p-2";
    readonly "layoutPadding3": "layout-padding-3";
    readonly "p3": "p-3";
    readonly "layoutPadding4": "layout-padding-4";
    readonly "p4": "p-4";
    readonly "layoutPadding5": "layout-padding-5";
    readonly "p5": "p-5";
    readonly "layoutPadding6": "layout-padding-6";
    readonly "p6": "p-6";
    readonly "layoutPadding7": "layout-padding-7";
    readonly "p7": "p-7";
    readonly "layoutPadding8": "layout-padding-8";
    readonly "p8": "p-8";
    readonly "layoutPaddingInline4": "layout-padding-inline-4";
    readonly "layoutPaddingBlock4": "layout-padding-block-4";
    readonly "layoutMargin0": "layout-margin-0";
    readonly "m0": "m-0";
    readonly "layoutMarginAuto": "layout-margin-auto";
    readonly "mAuto": "m-auto";
    readonly "layoutMarginInlineAuto": "layout-margin-inline-auto";
  };
  size: {
    readonly "layoutWidthFull": "layout-width-full";
    readonly "wFull": "w-full";
    readonly "layoutWidthFit": "layout-width-fit";
    readonly "layoutWidthMin": "layout-width-min";
    readonly "layoutWidthMax": "layout-width-max";
    readonly "layoutHeightFull": "layout-height-full";
    readonly "hFull": "h-full";
    readonly "layoutHeightScreen": "layout-height-screen";
    readonly "minHScreen": "min-h-screen";
    readonly "layoutSizeFull": "layout-size-full";
    readonly "layoutRatioSquare": "layout-ratio-square";
    readonly "layoutRatioVideo": "layout-ratio-video";
  };
  typography: {
    readonly "fontSans": "typography-font-sans";
    readonly "fontSerif": "typography-font-serif";
    readonly "fontMono": "typography-font-mono";
    readonly "size0": "typography-size-0";
    readonly "size1": "typography-size-1";
    readonly "size2": "typography-size-2";
    readonly "size3": "typography-size-3";
    readonly "size4": "typography-size-4";
    readonly "size5": "typography-size-5";
    readonly "size6": "typography-size-6";
    readonly "size7": "typography-size-7";
    readonly "lineTight": "typography-line-tight";
    readonly "lineSnug": "typography-line-snug";
    readonly "lineNormal": "typography-line-normal";
    readonly "lineLoose": "typography-line-loose";
    readonly "weightRegular": "typography-weight-regular";
    readonly "weightMedium": "typography-weight-medium";
    readonly "weightSemibold": "typography-weight-semibold";
    readonly "weightBold": "typography-weight-bold";
    readonly "letterTight": "typography-letter-tight";
    readonly "letterNormal": "typography-letter-normal";
    readonly "letterWide": "typography-letter-wide";
    readonly "alignStart": "typography-align-start";
    readonly "alignCenter": "typography-align-center";
    readonly "alignEnd": "typography-align-end";
    readonly "transformUppercase": "typography-transform-uppercase";
    readonly "transformLowercase": "typography-transform-lowercase";
    readonly "transformCapitalize": "typography-transform-capitalize";
    readonly "decorationNone": "typography-decoration-none";
    readonly "decorationUnderline": "typography-decoration-underline";
    readonly "decorationLineThrough": "typography-decoration-line-through";
    readonly "overflowTruncate": "typography-overflow-truncate";
    readonly "overflowWrap": "typography-overflow-wrap";
    readonly "balance": "typography-balance";
    readonly "pretty": "typography-pretty";
  };
  shape: {
    readonly "radius0": "shape-radius-0";
    readonly "radius1": "shape-radius-1";
    readonly "radius2": "shape-radius-2";
    readonly "radius3": "shape-radius-3";
    readonly "radius4": "shape-radius-4";
    readonly "radiusRound": "shape-radius-round";
    readonly "border0": "shape-border-0";
    readonly "border1": "shape-border-1";
    readonly "border2": "shape-border-2";
  };
  effect: {
    readonly "shadow0": "effect-shadow-0";
    readonly "shadow1": "effect-shadow-1";
    readonly "shadow2": "effect-shadow-2";
    readonly "shadow3": "effect-shadow-3";
    readonly "opacity0": "effect-opacity-0";
    readonly "opacity50": "effect-opacity-50";
    readonly "opacity100": "effect-opacity-100";
    readonly "blur0": "effect-blur-0";
    readonly "blur1": "effect-blur-1";
    readonly "blur2": "effect-blur-2";
    readonly "ring": "effect-ring";
    readonly "outlineOffset2": "effect-outline-offset-2";
  };
  animation: {
    readonly "transitionColors": "animation-transition-colors";
    readonly "transitionTransform": "animation-transition-transform";
    readonly "transitionOpacity": "animation-transition-opacity";
    readonly "transitionShadow": "animation-transition-shadow";
    readonly "transitionAll": "animation-transition-all";
    readonly "durationFast": "animation-duration-fast";
    readonly "durationNormal": "animation-duration-normal";
    readonly "durationSlow": "animation-duration-slow";
    readonly "easeStandard": "animation-ease-standard";
    readonly "easeIn": "animation-ease-in";
    readonly "easeOut": "animation-ease-out";
    readonly "fadeIn": "animation-fade-in";
    readonly "enter": "animation-enter";
  };
  interaction: {
    readonly "cursorDefault": "interaction-cursor-default";
    readonly "cursorPointer": "interaction-cursor-pointer";
    readonly "cursorNotAllowed": "interaction-cursor-not-allowed";
    readonly "pointerNone": "interaction-pointer-none";
    readonly "pointerAuto": "interaction-pointer-auto";
    readonly "selectNone": "interaction-select-none";
    readonly "selectText": "interaction-select-text";
    readonly "selectAll": "interaction-select-all";
    readonly "scrollAuto": "interaction-scroll-auto";
    readonly "scrollSmooth": "interaction-scroll-smooth";
    readonly "hidden": "interaction-hidden";
    readonly "invisible": "interaction-invisible";
    readonly "visible": "interaction-visible";
    readonly "srOnly": "interaction-sr-only";
    readonly "notSrOnly": "interaction-not-sr-only";
  };
  responsive: {
    readonly "smLayoutGrid": "sm:layout-grid";
    readonly "smLayoutDisplayFlex": "sm:layout-display-flex";
    readonly "smLayoutDisplayNone": "sm:layout-display-none";
    readonly "mdLayoutGrid": "md:layout-grid";
    readonly "mdLayoutDisplayFlex": "md:layout-display-flex";
    readonly "mdLayoutDisplayNone": "md:layout-display-none";
    readonly "lgLayoutGrid": "lg:layout-grid";
    readonly "lgLayoutDisplayFlex": "lg:layout-display-flex";
    readonly "lgLayoutDisplayNone": "lg:layout-display-none";
  };
  state: {
    readonly "hoverColorBg": "hover:color-bg";
    readonly "activeColorBg": "active:color-bg";
    readonly "hoverColorBorder": "hover:color-border";
    readonly "focusColorBorder": "focus:color-border";
    readonly "hoverColorActionBg": "hover:color-action-bg";
    readonly "hoverColorAccentBg": "hover:color-accent-bg";
    readonly "activeColorActionBg": "active:color-action-bg";
    readonly "activeColorAccentBg": "active:color-accent-bg";
    readonly "disabledColorBg": "disabled:color-bg";
    readonly "disabledColorFg": "disabled:color-fg";
    readonly "disabledColorBorder": "disabled:color-border";
    readonly "focusEffectRing": "focus:effect-ring";
    readonly "focusVisibleEffectRing": "focus-visible:effect-ring";
    readonly "focusWithinEffectRing": "focus-within:effect-ring";
    readonly "hoverInteractionCursorPointer": "hover:interaction-cursor-pointer";
    readonly "focusInteractionPointerAuto": "focus:interaction-pointer-auto";
    readonly "activeInteractionCursorDefault": "active:interaction-cursor-default";
    readonly "disabledInteractionCursorNotAllowed": "disabled:interaction-cursor-not-allowed";
    readonly "cqSmLayoutGrid": "cq-sm:layout-grid";
    readonly "cqSmLayoutDisplayFlex": "cq-sm:layout-display-flex";
    readonly "cqSmLayoutDisplayNone": "cq-sm:layout-display-none";
    readonly "cqMdLayoutGrid": "cq-md:layout-grid";
    readonly "cqMdLayoutDisplayFlex": "cq-md:layout-display-flex";
    readonly "cqMdLayoutDisplayNone": "cq-md:layout-display-none";
    readonly "cqLgLayoutGrid": "cq-lg:layout-grid";
    readonly "cqLgLayoutDisplayFlex": "cq-lg:layout-display-flex";
    readonly "cqLgLayoutDisplayNone": "cq-lg:layout-display-none";
  };
  misc: {
    readonly "block": "block";
    readonly "inline": "inline";
    readonly "inlineBlock": "inline-block";
    readonly "flex": "flex";
    readonly "inlineFlex": "inline-flex";
    readonly "inlineGrid": "inline-grid";
    readonly "grid": "grid";
    readonly "hidden": "hidden";
    readonly "itemsCenter": "items-center";
    readonly "justifyCenter": "justify-center";
    readonly "justifyBetween": "justify-between";
    readonly "px4": "px-4";
    readonly "py4": "py-4";
    readonly "mxAuto": "mx-auto";
    readonly "cursorDefault": "cursor-default";
    readonly "cursorPointer": "cursor-pointer";
    readonly "cursorNotAllowed": "cursor-not-allowed";
    readonly "pointerEventsNone": "pointer-events-none";
    readonly "pointerEventsAuto": "pointer-events-auto";
    readonly "selectNone": "select-none";
    readonly "selectText": "select-text";
    readonly "selectAll": "select-all";
    readonly "responsiveContainer": "responsive-container";
    readonly "responsiveContainerNamed": "responsive-container-named";
    readonly "sliderThumbWrapper": "slider-thumb-wrapper";
    readonly "enterFade0": "enter-fade-0";
    readonly "enterZoom96": "enter-zoom-96";
    readonly "enterSlideX50": "enter-slide-x-50";
    readonly "enterSlideY48": "enter-slide-y-48";
  };
};

export declare function createRoot(Fn: any): any;
export declare function createElement(type: any, ...args: any[]): any;
export declare function component(Fn: any, tagName?: string): any;
export declare const html: Record<string, (...args: any[]) => any>;
export declare function match(p: Element | null, s?: string): Element | null;
