import { component, createRoot, html } from '../../giant.js';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle,
  DialogDescription, DialogFooter, DialogAction, DialogCancel
} from './dialog.js';

const { div, section, h2, button } = html;

const nextTick = () => new Promise(resolve => setTimeout(resolve, 20));
// Dialogs have a 200ms exit animation, so we need a slightly longer wait for cleanup checks
const wait = (ms) => new Promise(resolve => setTimeout(resolve, ms));

// --- TEST UI SETUP ---
const DialogTestApp = component(function DialogTestApp() {
  return div({ class: 'dialog-test-wrapper', style: { display: 'flex', flexDirection: 'column', gap: '40px' } },

    section({ class: 'test-section' },
      h2('Standard Dialog'),

      // Assign an ID so we can directly select the Host node
      Dialog({ id: 'dialog-host', 'data-testid': 'dialog-standard' },
        DialogContent({ 'data-testid': 'dialog-content' },
          DialogHeader({},
            DialogTitle({}, 'Edit Profile'),
            DialogDescription({}, 'Make changes to your profile here. Click save when you are done.')
          ),
          div({ style: { padding: '1rem 0' } }, 'Dialog inner form content...'),
          DialogFooter({},
            DialogCancel({},
              button({ 'data-testid': 'btn-cancel' }, 'Cancel')
            ),
            DialogAction({ value: 'saved_data_123' },
              button({ 'data-testid': 'btn-save' }, 'Save Changes')
            )
          )
        )
      )
    )

  );
}, 'dialog-test-app');

// --- TEST RUNNER EXPORT ---
export async function testDialog(mountPoint, assert) {
  const appNode = await createRoot(DialogTestApp);
  mountPoint.appendChild(appNode);
  await nextTick();

  // 1. Get the Host wrapper generated by Giant.js (where the methods live)
  const dialogHost = document.getElementById('dialog-host');

  // 2. Get the Inner element which handles the CSS
  const dialogInner = appNode.querySelector('[data-testid="dialog-standard"]');

  // Ensure body overflow is clean before we start
  document.body.style.overflow = '';

  // ==========================================
  // --- INITIALIZATION TESTS ---
  // ==========================================
  assert(
    dialogInner.style.display === 'none',
    'Initialization: Dialog is hidden (display: none) by default'
  );

  assert(
    typeof dialogHost.open === 'function' && typeof dialogHost.close === 'function',
    'API: Component exposes public open() and close() methods on the host node'
  );

  // ==========================================
  // --- OPEN & ACTION TESTS ---
  // ==========================================

  // 1. Open the dialog FIRST using the host wrapper
  let openPromise = dialogHost.open();
  await nextTick();

  // NOW the contents exist in the DOM, so we can safely query them!
  const btnSave = appNode.querySelector('[data-testid="btn-save"]');

  assert(
    dialogInner.style.display === 'block',
    'API: calling open() makes the dialog visible'
  );

  assert(
    document.body.style.overflow === 'hidden',
    'Accessibility: calling open() locks the document body scroll'
  );

  // 2. Click the Action Button
  btnSave.click();

  // 3. Wait exactly one tick for the proxy state to trigger the animation re-render
  await nextTick();

  // 4. Assert the animation state via data-attributes instead of inline styles
  assert(
    dialogInner.style.pointerEvents === 'none' && dialogInner.getAttribute('data-dialog-state') === 'closing',
    'Animation: Dialog disables pointer events and enters "closing" state immediately upon closing'
  );

  // 5. NOW await the 200ms promise resolution
  let result = await openPromise;

  assert(
    result === 'saved_data_123',
    'DialogAction: Clicking an action button resolves the open() Promise with its data-value'
  );

  // Wait one final tick for the DOM to patch the closed state
  await nextTick();

  assert(
    dialogInner.style.display === 'none' && document.body.style.overflow === '',
    'Lifecycle: After animation, dialog is hidden and body scroll is restored'
  );

  // ==========================================
  // --- CANCEL & CLOSE TESTS ---
  // ==========================================

  // Test Cancel Button
  openPromise = dialogHost.open();
  await nextTick();

  // Re-query the cancel button because the DOM nodes were destroyed and recreated!
  appNode.querySelector('[data-testid="btn-cancel"]').click();
  result = await openPromise;

  assert(
    result === null,
    'DialogCancel: Clicking a cancel button resolves the open() Promise with null'
  );

  await wait(250); // wait for exit

  // Test built-in X button
  openPromise = dialogHost.open();
  await nextTick();

  appNode.querySelector('button[data-dialog-close="true"]').click();
  result = await openPromise;

  assert(
    result === null,
    'DialogContent: Built-in X button resolves the open() Promise with null'
  );

  await wait(250);

  // ==========================================
  // --- OVERLAY CLICK TESTS ---
  // ==========================================
  openPromise = dialogHost.open();
  await nextTick();

  // Simulate clicking the background overlay (which is the dialog inner element itself)
  dialogInner.dispatchEvent(new MouseEvent('click', { bubbles: true }));
  result = await openPromise;

  assert(
    result === null,
    'Overlay: Clicking the backdrop (modal mode) resolves the Promise with null and closes the dialog'
  );

  await wait(250);

  // ==========================================
  // --- PROGRAMMATIC CLOSE TESTS ---
  // ==========================================
  openPromise = dialogHost.open();
  await nextTick();

  // Forcefully close the dialog via the public API instead of clicking
  dialogHost.close('programmatic_override');
  result = await openPromise;

  assert(
    result === 'programmatic_override',
    'API: Calling close(value) programmatically resolves the Promise with the value and closes the dialog'
  );

  await wait(250); // Final cleanup tick
}
